pokemons = [
    'Bulbizarre', 'Herbizarre', 'Florizarre', 'Salamèche', 'Reptincel', 'Dracaufeu', 'Carapuce', 'Carabaffe', 'Tortank',
    'Chenipan', 'Chrysacier', 'Papilusion', 'Aspicot', 'Coconfort', 'Dardargnan', 'Roucool', 'Roucoups', 'Roucarnage',
    'Rattata', 'Rattatac', 'Piafabec', 'Rapasdepic', 'Abo', 'Arbok', 'Pikachu', 'Raichu', 'Sabelette', 'Sablaireau',
    'Nidoran♀', 'Nidorina', 'Nidoqueen', 'Nidoran♂', 'Nidorino', 'Nidoking', 'Mélofée', 'Mélodelfe', 'Goupix',
    'Feunard', 'Rondoudou', 'Grodoudou', 'Nosferapti', 'Nosferalto', 'Mystherbe', 'Ortide', 'Rafflesia', 'Paras',
    'Parasect', 'Mimitoss', 'Aéromite', 'Taupiqueur', 'Triopikeur', 'Miaouss', 'Persian', 'Psykokwak', 'Akwakwak',
    'Férosinge', 'Colossinge', 'Caninos', 'Arcanin', 'Ptitard', 'Tétarte', 'Tartard', 'Abra', 'Kadabra', 'Alakazam',
    'Machoc', 'Machopeur', 'Mackogneur', 'Chétiflor', 'Boustiflor', 'Empiflor', 'Tentacool', 'Tentacruel', 'Racaillou',
    'Gravalanch', 'Grolem', 'Ponyta', 'Galopa', 'Ramoloss', 'Flagadoss', 'Magneti', 'Magneton', 'Canarticho', 'Doduo',
    'Dodrio', 'Otaria', 'Lamantine', 'Tadmorv', 'Grotadmorv', 'Kokiyas', 'Crustabri', 'Fantominus', 'Spectrum',
    'Ectoplasma', 'Onix', 'Soporifik', 'Hypnomade', 'Krabby', 'Krabboss', 'Voltorbe', 'Electrode', 'Noeunoeuf',
    'Noadkoko', 'Osselait', 'Ossatueur', 'Kicklee', 'Tygnon', 'Excelangue', 'Smogo', 'Smogogo', 'Rhinocorne',
    'Rhinoféros', 'Leveinard', 'Saquedeneu', 'Kangourex', 'Hypotrempe', 'Hypocéan', 'Poissirène', 'Poissoroy', 'Stari',
    'Staross', 'Mr.Mime', 'Insécateur', 'Lippoutou', 'Elektek', 'Magmar', 'Scarabrute', 'Tauros', 'Magicarpe',
    'Léviator', 'Lokhlass', 'Métamorph', 'Evoli', 'Aquali', 'Voltali', 'Pyroli', 'Porygon', 'Amonita', 'Amonistar',
    'Kabuto', 'Kabutops', 'Ptéra', 'Ronflex', 'Artikodin', 'Electhor', 'Sulfura', 'Minidraco', 'Draco', 'Dracolosse',
    'Mewtwo', 'Mew', 'Germignon', 'Macronium', 'Méganium', 'Héricendre', 'Feurisson', 'Typhlosion', 'Kaïminus',
    'Crocrodil', 'Aligatueur', 'Fouinette', 'Fouinar', 'Hoot-hoot', 'Noarfang', 'Coxy', 'Coxyclaque', 'Mimigal',
    'Migalos', 'Nostenfer', 'Loupio', 'Lanturn', 'Pichu', 'Mélo', 'Toudoudou', 'Togépi', 'Togétic', 'Natu', 'Xatu',
    'Wattouat', 'Lainergie', 'Pharamp', 'Joliflor', 'Marill', 'Azumarill', 'Simularbre', 'Tarpaud', 'Granivol',
    'Floravol', 'Cotovol', 'Capumain', 'Tournegrin', 'Héliatronc', 'Yanma', 'Axoloto', 'Maraiste', 'Mentali', 'Noctali',
    'Cornebre', 'Roigada', 'Feuforêve', 'Zarbi', 'Qulbutoke', 'Girafarig', 'Pomdepic', 'Foretress', 'Insolourdo',
    'Scorplane', 'Steelix', 'Snubbull', 'Granbull', 'Qwilfish', 'Cizayox', 'Caratroc', 'Scarhino', 'Farfuret',
    'Teddiursa', 'Ursaring', 'Limagma', 'Volcaropod', 'Marcacrain', 'Cochignon', 'Corayon', 'Remoraid', 'Octillery',
    'Cadoizo', 'Demanta', 'Airmure', 'Malosse', 'Démolosse', 'Hyporoi', 'Phanpy', 'Donphan', 'Porygon2', 'Cerfrousse',
    'Queulorior', 'Débugant', 'Kapoera', 'Lippouti', 'Elekid', 'Magby', 'Ecremeuh', 'Leuphorie', 'Raïkou', 'Enteï',
    'Suicune', 'Embrylex', 'Ymphect', 'Tyranocif', 'Lugia', 'Ho-oh', 'Célébi', 'Arcko', 'Massko', 'Jungko', 'Poussifeu',
    'Galifeu', 'Brasegali', 'Gobou', 'Flobio', 'Laggron', 'Medhyena', 'Grahyena', 'Zigzaton', 'Lineon', 'Chenipotte',
    'Armulys', 'Charmillon', 'Blindalys', 'Papinox', 'Nenupiot', 'Lombre', 'Ludicolo', 'Grainipiot', 'Pifeuil',
    'Tengalice', 'Nirondelle', 'Heledelle', 'Goelise', 'Bekipan', 'Tarsal', 'Kirlia', 'Gardevoir', 'Arakdo', 'Maskadra',
    'Balignon', 'Chapignon', 'Parecool', 'Vigoroth', 'Monaflemit', 'Ningale', 'Ninjask', 'Munja', 'Chuchmur', 'Ramboum',
    'Brouhabam', 'Makuhita', 'Hariyama', 'Azurill', 'Tarinor', 'Skitty', 'Delcatty', 'Tenefix', 'Mysdibule', 'Galekid',
    'Galegon', 'Galeking', 'Meditikka', 'Charmina', 'Dynavolt', 'Elecsprint', 'Posipi', 'Negapi', 'Muciole', 'Lumivole',
    'Roselia', 'Gloupti', 'Avaltout', 'Carvanha', 'Sharpedo', 'Wailmer', 'Wailord', 'Chamallot', 'Camerupt', 'Chartor',
    'Spoink', 'Groret', 'Spinda', 'Kraknoix', 'Vibrannif', 'Libegon', 'Cacnea', 'Cacturne', 'Tylton', 'Altaria',
    'Mangriff', 'Seviper', 'Seleroc', 'Solaroc', 'Barloche', 'Barbicha', 'Ecrapince', 'Colhomar', 'Balbuto', 'Kaorine',
    'Lilia', 'Vacilys', 'Anorith', 'Armaldo', 'Barpau', 'Milobellus', 'Morpheo', 'Kecleon', 'Polichombr', 'Branette',
    'Skelenox', 'Teraclope', 'Tropius', 'Eoko', 'Absol', 'Okéoké', 'Stalgamin', 'Oniglali', 'Obalie', 'Phogleur',
    'Kaimorse', 'Coquiperl', 'Serpang', 'Rosabyss', 'Relicanth', 'Lovdisc', 'Draby', 'Drakhaus', 'Drattak', 'Terhal',
    'Metang', 'Metalosse', 'Regirock', 'Regice', 'Registeel', 'Latias', 'Latios', 'Kyogre', 'Groudon', 'Rayquaza',
    'Jirachi', 'Deoxys', 'Tortipouss', 'Boskara', 'Torterra', 'Ouisticram', 'Chimpenfeu', 'Simiabraz', 'Tiplouf',
    'Prinplouf', 'Pingoleon', 'Étourmi', 'Étourvol', 'Étouraptor', 'Keunotor', 'Castorno', 'Crikzik', 'Melocrik',
    'Lixy', 'Luxio', 'Luxray', 'Rozbouton', 'Roserade', 'Kranidos', 'Charkos', 'Dinoclier', 'Bastiodon', 'Cheniti',
    'Cheniselle', 'Papilord', 'Apitrini', 'Apireine', 'Pachirisu', 'Mustebouée', 'Musteflott', 'Ceribou', 'Ceriflor',
    'Sancoki', 'Tritosor', 'Capidextre', 'Baudrive', 'Grodrive', 'Laporeille', 'Lockpin', 'Magirêve', 'Corboss',
    'Chaglam', 'Chaffreux', 'Korillon', 'Moufouette', 'Moufflair', 'Archeomire', 'Archeodong', 'Manzaï', 'MimeJr.',
    'Ptiravi', 'Pijako', 'Spiritomb', 'Griknot', 'Carmache', 'Carchacrok', 'Goinfrex', 'Riolu', 'Lucario', 'Hippopotas',
    'Hippodocus', 'Rapion', 'Drascore', 'Cradopaud', 'Coatox', 'Vortente', 'Ecayon', 'Lumineon', 'Babimanta', 'Blizzi',
    'Blizzaroi', 'Dimoret', 'Magnezone', 'Coudlangue', 'Rhinastoc', 'Bouldeneu', 'Elekable', 'Maganon', 'Togekiss',
    'Yanmega', 'Phyllali', 'Givrali', 'Scorvol', 'Mammochon', 'Porygon-Z', 'Gallame', 'Tarinorme', 'Noctunoir',
    'Momartik', 'Motisma', 'Crehelf', 'Crefollet', 'Crefadet', 'Dialga', 'Palkia', 'Heatran', 'Regigigas', 'Giratina',
    'Cresselia', 'Phione', 'Manaphy', 'Darkrai', 'Shaymin', 'Arceus']
